const token = document.querySelector('meta[name="story-studio-token"]').content;
const state = { projectId: null, revisionId: null, jobId: null };
const $ = (id) => document.getElementById(id);
const setNotice = (text, kind = '') => { $('notice').textContent = text; $('notice').className = `notice ${kind}`; };
const showDiagnostics = (diagnostics = []) => { $('diagnostics').innerHTML = diagnostics.length ? diagnostics.map((d) => `<div class="diag ${String(d.code || '').includes('PASS') ? 'pass' : ''}"><code>${escapeHtml(d.code || 'INFO')}</code><span>${escapeHtml(d.message || '')}</span></div>`).join('') : '<div class="empty">尚无诊断</div>'; };
const escapeHtml = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

async function api(path, options = {}) {
  const response = await fetch(`/api/v1${path}`, { ...options, headers: { 'content-type': 'application/json', 'x-story-studio-token': token, ...(options.headers || {}) } });
  const body = await response.json(); if (!response.ok || !body.ok) { const error = body.diagnostics?.[0] || { message: `HTTP ${response.status}` }; throw new Error(`${error.code || response.status}: ${error.message}`); } return body;
}
async function readJson(file) { if (!file) throw new Error('请选择 JSON 文件'); return JSON.parse(await file.text()); }
async function requireRevision() { if (!state.projectId || !state.revisionId) throw new Error('请先创建项目并导入 revision'); }
async function refreshRevision() { if (!state.projectId || !state.revisionId) return; const body = await api(`/projects/${state.projectId}/revisions/${state.revisionId}`); $('revisionInfo').textContent = JSON.stringify({ revisionId: body.data.revisionId, status: body.data.status, build: body.data.build, validation: body.data.validation, generation: body.data.generation }, null, 2); }
async function runJob(operation, extra = {}) { await requireRevision(); const body = await api(`/projects/${state.projectId}/jobs`, { method: 'POST', body: JSON.stringify({ revisionId: state.revisionId, operation, ...extra }) }); state.jobId = body.data.jobId; $('jobStatus').textContent = `${state.jobId} / queued`; for (let i = 0; i < 200; i += 1) { await new Promise((resolve) => setTimeout(resolve, 100)); const job = await api(`/jobs/${state.jobId}`); $('jobStatus').textContent = `${job.data.jobId} / ${job.data.status}`; if (['succeeded', 'failed', 'cancelled'].includes(job.data.status)) { showDiagnostics(job.data.diagnostics || []); if (job.data.status !== 'succeeded') throw new Error(job.data.diagnostics?.[0]?.message || 'job failed'); await refreshRevision(); return job.data; } } throw new Error('job polling timeout'); }
async function action(fn) { try { await fn(); setNotice('完成', 'success'); } catch (error) { setNotice(error.message, 'error'); showDiagnostics([{ code: 'UI_ERROR', message: error.message }]); } }

$('capabilities').onclick = () => action(async () => { const body = await api('/capabilities'); $('runtime').textContent = `engine ${body.data.runtime.engineMajor} / template ${body.data.runtime.templateVersion}`; setNotice(`能力已读取：${body.data.actions.join(' · ')}`, 'success'); });
$('create').onclick = () => action(async () => { const sourceText = $('sourceText').value; if (!sourceText.trim()) throw new Error('请先粘贴故事片段'); const body = await api('/projects', { method: 'POST', body: JSON.stringify({ sourceText, sourceId: 'studio-source', title: $('title').value, author: $('author').value, extent: 'excerpt', boundary: $('boundary').value, usage: $('usage').value, authorizationNote: $('authorizationNote').value || '待人工核对的本地原型', ...( $('verifiedUrl').value ? { verifiedUrl: $('verifiedUrl').value } : {}) }) }); state.projectId = body.data.projectId; state.revisionId = body.data.revisionId; $('projectMeta').textContent = `${state.projectId} · source ${body.data.sourceDigest.slice(0, 12)}…`; $('revisionId').textContent = state.revisionId; setNotice('项目已创建，请导入 analysis + blueprint。', 'success'); });
$('import').onclick = () => action(async () => { if (!state.projectId) throw new Error('请先创建项目'); const analysis = await readJson($('analysisFile').files[0]); const blueprint = await readJson($('blueprintFile').files[0]); const body = await api(`/projects/${state.projectId}/revisions`, { method: 'POST', body: JSON.stringify({ baseRevisionId: state.revisionId, analysis, blueprint }) }); state.revisionId = body.data.revisionId; $('revisionId').textContent = state.revisionId; await refreshRevision(); setNotice('revision 已锁定，可以构建。', 'success'); });
$('build').onclick = () => action(async () => { await runJob('build'); setNotice('构建成功，可以静态校验或试玩。', 'success'); });
$('validate').onclick = () => action(async () => { const job = await runJob('validate-static'); if (job.result?.status === 'valid') setNotice('静态校验通过。', 'success'); });
$('preview').onclick = () => action(async () => { await requireRevision(); const body = await api(`/projects/${state.projectId}/revisions/${state.revisionId}/preview`); window.open(body.data.url, '_blank', 'noopener'); setNotice(`已打开 ${state.revisionId} 的指定预览。`, 'success'); });
$('export').onclick = () => action(async () => { const job = await runJob('export', { audience: 'private' }); setNotice(`已导出：${job.result?.out || 'workspace exports'}`, 'success'); });
for (const decision of ['approve', 'reject']) $(decision).onclick = () => action(async () => { await requireRevision(); await api(`/projects/${state.projectId}/reviews`, { method: 'POST', body: JSON.stringify({ revisionId: state.revisionId, scope: $('reviewScope').value, decision, note: $('reviewNote').value || `${decision} recorded in local Studio` }) }); setNotice(`${$('reviewScope').value} 审阅已记录：${decision}`, 'success'); });

action(async () => { const body = await api('/capabilities'); $('runtime').textContent = `engine ${body.data.runtime.engineMajor} / template ${body.data.runtime.templateVersion}`; setNotice('本地 Studio 已就绪。', 'success'); });
